-- ============================================================
--  Cyvathon — Citizen Sites migration
--  A directory of the websites citizens have built. Each citizen may
--  list up to five; other citizens star them, visit them, and flag
--  broken or unsuitable ones for the President to review.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

create table if not exists citizen_sites (
    id          bigint generated by default as identity primary key,
    owner       text not null,
    url         text not null,              -- always https://
    url_key     text not null unique,       -- host + path, lower-cased, no www. or trailing slash:
                                            -- so one site is only ever listed once
    title       text not null default '',
    description text default '',
    category    text not null default 'other',
    -- portfolio | blog | project | game | business | tool | art | other
    cyvapay     boolean not null default false,  -- owner says it takes Cyvapay; the badge
                                                 -- only shows if they also have a live link
    stars       integer not null default 0,
    clicks      integer not null default 0,      -- visits through /sites/go, owner's own excluded
    reports     integer not null default 0,
    hidden      boolean not null default false,  -- pulled after enough reports, until the
                                                 -- President restores or removes it
    created_at  timestamptz default now(),
    updated_at  timestamptz default now()
);
create index if not exists idx_sites_owner   on citizen_sites (owner);
create index if not exists idx_sites_created on citizen_sites (created_at desc);

create table if not exists site_stars (
    id          bigint generated by default as identity primary key,
    site_id     bigint not null references citizen_sites(id) on delete cascade,
    username    text not null,
    created_at  timestamptz default now(),      -- "Site of the Week" counts the last seven days
    unique (site_id, username)
);
create index if not exists idx_site_stars_when on site_stars (created_at desc);

create table if not exists site_reports (
    id          bigint generated by default as identity primary key,
    site_id     bigint not null references citizen_sites(id) on delete cascade,
    username    text not null,
    reason      text not null default 'broken', -- broken | inappropriate | scam | other
    created_at  timestamptz default now(),
    unique (site_id, username)                  -- one report per citizen per site
);
