-- ============================================================
--  Cyvathon — Account security migration
--  Password changes, per-account lockout, login alerts and history,
--  a payment PIN, and the President's security desk.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

-- ---- on each citizen -------------------------------------------------
alter table cybucks add column if not exists must_change_pw     boolean default false;
alter table cybucks add column if not exists pw_changed_at      timestamptz;
-- every signed-in device carries this number; raising it signs them all out
alter table cybucks add column if not exists session_version    integer default 0;
-- wrong passwords in a row, and the lock they earn
alter table cybucks add column if not exists login_fails        integer default 0;
alter table cybucks add column if not exists login_locked_until timestamptz;
-- locked by the President (separate from `banned`, which is permanent)
alter table cybucks add column if not exists locked             boolean default false;
alter table cybucks add column if not exists lock_reason        text;
alter table cybucks add column if not exists locked_at          timestamptz;
alter table cybucks add column if not exists locked_by          text;
-- the payment PIN, hashed the same way passwords are
alter table cybucks add column if not exists pin_hash           text;
alter table cybucks add column if not exists pin_set_at         timestamptz;
alter table cybucks add column if not exists pin_fails          integer default 0;
alter table cybucks add column if not exists pin_locked_until   timestamptz;

-- ---- every login, good or bad ---------------------------------------
create table if not exists login_events (
    id         bigint generated by default as identity primary key,
    username   text not null,
    ok         boolean not null default false,
    kind       text not null default 'login',
    -- login | fail | lockout | locked | locked-account | password-change
    -- | admin-reset | admin-logout | admin-lock | admin-unlock | pin-lock
    ip         text,
    ua         text,
    note       text default '',
    created_at timestamptz default now()
);
create index if not exists idx_login_events_user on login_events (username, id desc);
create index if not exists idx_login_events_when on login_events (created_at desc);

-- ---- the President's lever for the PIN threshold ---------------------
alter table config add column if not exists pin_threshold numeric default 500;
