-- ============================================================
--  Cyvathon — National Timeline migration
--  The founding events live in main.py as the canonical record and
--  cannot be deleted. This table is for everything that happens next.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

create table if not exists timeline_events (
    id          bigint generated by default as identity primary key,
    happened_on date not null,
    title       text not null,
    body        text default '',
    kind        text not null default 'event',
    -- founding | website | treaty | territory | institution | election | conflict | event
    added_by    text not null,
    created_at  timestamptz default now()
);

create index if not exists idx_timeline_when on timeline_events (happened_on);
