-- ============================================================
--  Cyvathon — Interests + Videos + Blogs migration
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
--
--  ALSO (for uploading videos from your computer):
--    Supabase → Storage → New bucket → name it "videos" → make it PUBLIC.
--    (The app tries to create it automatically, but making it manually is safest.)
-- ============================================================

-- 1) Interests: a comma-separated list of interest keys on each citizen
alter table cybucks add column if not exists interests text default '';

-- 1b) Account type: 'citizen' or 'micronation' (+ whether a nation wants an alliance)
-- 1c) Flight Sim: best score + last daily-bonus date
alter table cybucks add column if not exists flight_best      numeric default 0;
alter table cybucks add column if not exists flight_bonus_day text default '';

alter table cybucks add column if not exists account_type  text default 'citizen';
alter table cybucks add column if not exists ally_interest boolean default false;
alter table cybucks add column if not exists allied        boolean default false;  -- President-confirmed alliance

-- 2) Videos platform
create table if not exists videos (
    id          bigint generated by default as identity primary key,
    username    text not null,
    title       text not null,
    url         text not null,          -- embed-ready URL (youtube/embed or direct file)
    kind        text default 'youtube', -- 'youtube' | 'file'
    description text default '',
    created_at  timestamptz default now()
);
create index if not exists idx_videos_created on videos (id desc);
alter table videos add column if not exists views  bigint default 0;   -- view counter (YouTube-style watch page)
alter table videos add column if not exists shares bigint default 0;   -- share counter

create table if not exists video_comments (
    id         bigint generated by default as identity primary key,
    video_id   bigint not null,
    username   text not null,
    body       text not null,
    created_at timestamptz default now()
);
create index if not exists idx_video_comments on video_comments (video_id);

-- 3) Blogs platform
create table if not exists blogs (
    id         bigint generated by default as identity primary key,
    username   text not null,
    title      text not null,
    body       text not null,
    created_at timestamptz default now()
);
create index if not exists idx_blogs_created on blogs (id desc);
alter table blogs add column if not exists shares bigint default 0;   -- share counter

create table if not exists blog_comments (
    id         bigint generated by default as identity primary key,
    blog_id    bigint not null,
    username   text not null,
    body       text not null,
    created_at timestamptz default now()
);
create index if not exists idx_blog_comments on blog_comments (blog_id);

-- 4) Mail (Gmail-style: one message, many recipients, per-recipient state)
create table if not exists mail (
    id         bigint generated by default as identity primary key,
    sender     text not null,
    subject    text default '(no subject)',
    body       text not null,
    thread_id  bigint,                       -- groups a reply with its conversation
    created_at timestamptz default now()
);
alter table mail add column if not exists thread_id bigint;   -- for existing installs
create index if not exists idx_mail_sender on mail (sender, id desc);
create index if not exists idx_mail_thread on mail (thread_id);

create table if not exists mail_recipients (
    id        bigint generated by default as identity primary key,
    mail_id   bigint not null,
    username  text not null,
    read      boolean default false,
    starred   boolean default false,
    archived  boolean default false,
    unique (mail_id, username)
);
create index if not exists idx_mailrcpt_user on mail_recipients (username, id desc);

create table if not exists blog_likes (
    id         bigint generated by default as identity primary key,
    blog_id    bigint not null,
    username   text not null,
    created_at timestamptz default now(),
    unique (blog_id, username)
);
create index if not exists idx_blog_likes on blog_likes (blog_id);

-- 6) Bluff — multiplayer card game with Cybucks betting
create table if not exists bluff_games (
    id         bigint generated by default as identity primary key,
    status     text default 'waiting',      -- 'waiting' | 'playing' | 'done'
    host       text not null,
    ante       numeric default 0,
    pot        numeric default 0,
    state      jsonb  default '{}',          -- players, hands, pile, turn, claim, log…
    winner     text,
    created_at timestamptz default now()
);
create index if not exists idx_bluff_status on bluff_games (status, id desc);

-- 7) Flight Sim live multiplayer presence (ephemeral; rows expire by timestamp)
create table if not exists flight_presence (
    username   text primary key,
    x  double precision default 0, y  double precision default 0, z  double precision default 0,
    qx double precision default 0, qy double precision default 0, qz double precision default 0, qw double precision default 1,
    spd        double precision default 0,
    updated_at double precision default 0
);
create index if not exists idx_flight_presence on flight_presence (updated_at);

-- ============================================================
-- 5) The Registry — classified dossier/files system (Athena · Office of Records)
--    Per-file access control: visibility = 'public' (all citizens) |
--    'cleared' (any sworn officer) | 'named' (only usernames in `allowed`,
--    stored comma-wrapped e.g. ",alice,bob,").
-- ============================================================
create table if not exists registry_files (
    id             bigint generated by default as identity primary key,
    title          text not null,
    subject        text default '',
    directorate    text default '',
    classification text default 'CONFIDENTIAL',
    body           text not null,
    visibility     text default 'cleared',   -- 'public' | 'cleared' | 'named'
    allowed        text default '',           -- comma-wrapped usernames for 'named'
    author         text not null,
    created_at     timestamptz default now()
);
create index if not exists idx_registry_files on registry_files (id desc);

create table if not exists registry_officers (
    id         bigint generated by default as identity primary key,
    username   text not null unique,
    grade      text default 'C-2',
    role       text default 'Officer',
    created_at timestamptz default now()
);
create index if not exists idx_registry_officers on registry_officers (username);

create table if not exists registry_bulletins (
    id         bigint generated by default as identity primary key,
    title      text not null,
    body       text not null,
    priority   text default 'ROUTINE',        -- 'ROUTINE' | 'IMMEDIATE'
    visibility text default 'cleared',         -- 'public' | 'cleared'
    allowed    text default '',
    author     text not null,
    created_at timestamptz default now()
);
create index if not exists idx_registry_bulletins on registry_bulletins (id desc);

create table if not exists registry_requests (
    id         bigint generated by default as identity primary key,
    username   text not null,
    note       text default '',
    status     text default 'pending',         -- 'pending' | 'approved' | 'denied'
    created_at timestamptz default now()
);
create index if not exists idx_registry_requests on registry_requests (username, id desc);
