-- ============================================================
--  Cyvathon — Cabinet Powers migration
--  Ministers get real authority: operational duties they carry out
--  themselves, and policy changes that need Presidential assent.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

-- ------------------------------------------------------------
--  POLICY PROPOSALS — a minister asks to move a national lever.
--  Nothing changes until the President assents; the proposal stores
--  the value at the time it was raised so the President can see
--  exactly what they are agreeing to.
-- ------------------------------------------------------------
create table if not exists policy_proposals (
    id            bigint generated by default as identity primary key,
    ministry      text not null default '',   -- the ministry that raised it
    portfolio     text not null default '',   -- defence | finance | transport | justice
    minister      text not null,
    field         text not null,              -- the config column being moved
    current_value numeric,                    -- value when the proposal was raised
    proposed_value numeric not null,
    reason        text default '',
    status        text not null default 'pending',  -- pending | approved | rejected | withdrawn
    decided_by    text,
    decided_at    timestamptz,
    decision_note text default '',
    created_at    timestamptz default now()
);

create index if not exists idx_proposals_status on policy_proposals (status, created_at desc);
create index if not exists idx_proposals_minister on policy_proposals (minister, created_at desc);
