-- ============================================================
--  Cyvathon — Cyvashield (National Insurance) migration
--  Free cover for every citizen; the President adjudicates claims.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

-- ------------------------------------------------------------
-- 1) POLICIES — one per citizen. Cover is free; the plan only
--    decides how much can be claimed and how often.
-- ------------------------------------------------------------
create table if not exists insurance_policies (
    id           bigint generated by default as identity primary key,
    username     text not null unique,
    plan         text not null default 'basic',   -- basic | standard | full
    active       boolean not null default true,
    enrolled_at  timestamptz default now(),
    switched_at  timestamptz,                     -- last plan change
    claims_paid  numeric not null default 0,      -- lifetime CB paid out
    claims_count integer not null default 0
);

create index if not exists idx_policies_active on insurance_policies (active);


-- ------------------------------------------------------------
-- 2) CLAIMS — a citizen reports a loss, the President rules on it.
--    ref_kind/ref_id optionally tie the claim to something the site
--    already knows about (a Cyvazon parcel, a marketplace sale, a card
--    trade), which lets the admin panel fact-check the story.
-- ------------------------------------------------------------
create table if not exists insurance_claims (
    id            bigint generated by default as identity primary key,
    username      text not null,
    plan          text not null default 'basic',    -- plan held when filed
    category      text not null,                    -- parcel | market | theft | scam | cards | other
    ref_kind      text default '',                  -- delivery | market | card_trade | ''
    ref_id        bigint,
    amount        numeric not null default 0,       -- CB claimed
    amount_paid   numeric not null default 0,       -- CB actually awarded
    description   text not null default '',
    evidence_url  text default '',
    accused       text default '',                  -- who the citizen says did it
    status        text not null default 'open',     -- open | approved | rejected | fraudulent
    decided_by    text,
    decided_at    timestamptz,
    decision_note text default '',
    created_at    timestamptz default now()
);

create index if not exists idx_claims_status on insurance_claims (status, created_at desc);
create index if not exists idx_claims_user   on insurance_claims (username, created_at desc);


-- ------------------------------------------------------------
-- 3) CONFIG — the President tunes the scheme from the admin panel.
--    insurance_levy defaults to 0: cover is genuinely free and paid
--    out of general Treasury revenue. Raise it only if payouts start
--    outrunning what the Treasury can carry.
-- ------------------------------------------------------------
alter table config add column if not exists insurance_open  boolean default true;
alter table config add column if not exists insurance_levy   numeric default 0;

insert into config (id) values (1) on conflict (id) do nothing;
