-- ============================================================
--  Cyvathon — the Corps (enlistment)
--  Citizens apply to defend the Republic in one of two branches: Field or
--  Cyber. The Quartermaster accepts or turns them away; an accepted soldier
--  is paid a one-time 500 CB and wears a Corps badge on their profile.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

create table if not exists corps_members (
    id          bigint generated by default as identity primary key,
    username    text not null,
    branch      text not null default 'field',    -- 'field' | 'cyber'
    experience  text default '',                  -- cyber: ethical-hacking / coding background
    status      text not null default 'pending',  -- pending | accepted | rejected
    decision_note text default '',                -- the Quartermaster's note
    decided_by  text,
    decided_at  timestamptz,
    badge_paid  boolean not null default false,
    created_at  timestamptz default now()
);
create index if not exists idx_corps_user on corps_members (username, id desc);
create index if not exists idx_corps_status on corps_members (status, id desc);
