-- ============================================================
--  Cyvathon — The National Pen Reserve migration
--  Citizens donate G2 pens to the state; the state pays for them.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

-- ------------------------------------------------------------
-- 1) DONATIONS — a citizen pledges pens, hands them over, and the
--    Registrar confirms receipt before a single Cybuck is paid.
--    Nothing is paid on a pledge alone: the whole point of a reserve
--    is that the asset is actually in the vault.
-- ------------------------------------------------------------
create table if not exists pen_donations (
    id            bigint generated by default as identity primary key,
    username      text not null,
    count         integer not null default 1,
    condition     text not null default 'working',  -- working | dry | broken
    note          text default '',
    status        text not null default 'pledged',  -- pledged | received | rejected | cancelled
    rate          numeric not null default 400,     -- CB per pen at pledge time
    counted       integer not null default 0,       -- pens the Registrar actually accepted
    amount_paid   numeric not null default 0,
    delivery_id   bigint,                           -- Cyvazon parcel, if sent that way
    decided_by    text,
    decided_at    timestamptz,
    decision_note text default '',
    created_at    timestamptz default now()
);

create index if not exists idx_pen_status on pen_donations (status, created_at desc);
create index if not exists idx_pen_user   on pen_donations (username, created_at desc);


-- ------------------------------------------------------------
-- 2) THE VAULT — how many pens the Republic actually holds.
--    This is the hard asset behind the Cybuck, so it lives on the
--    Treasury row alongside the currencies and counts toward GDP.
-- ------------------------------------------------------------
alter table treasury add column if not exists pens integer default 0;


-- ------------------------------------------------------------
-- 3) CONFIG — the President sets what the Reserve pays.
--    400 CB is deliberately far above what a pen costs: the Reserve
--    isn't buying stationery, it's buying currency backing.
-- ------------------------------------------------------------
alter table config add column if not exists pen_rate numeric default 400;
alter table config add column if not exists pen_open boolean default true;

insert into config (id) values (1) on conflict (id) do nothing;
