-- ============================================================
--  Cyvathon — Football Card Trading ("Packets") migration
--  Match Attax packets, wishlists and citizen-to-citizen trades.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

-- ------------------------------------------------------------
-- 1) CARD PACKET — every citizen's collection.
--    Player details are pulled from an online football database at
--    add-time and denormalised here, so a packet still renders even
--    if the upstream database is unreachable later.
-- ------------------------------------------------------------
create table if not exists card_packet (
    id          bigint generated by default as identity primary key,
    owner       text not null,
    player_id   text,                       -- upstream database id (may be null for manual adds)
    player_name text not null,
    team        text default '',
    nationality text default '',
    position    text default '',
    image_url   text default '',            -- player cutout/photo from the online database
    card_image  text default '',            -- photo of the owner's actual card
    card_url    text default '',            -- optional link to a reference page for the card
    -- A Match Attax card is a SUBSET (Base, Captain, 100 Club…) printed in a
    -- FINISH (Base, Black Edge, Gold Edge…). Both are kept, because collectors
    -- name and value a card using both.
    subset      text not null default 'base',
    edition     text not null default 'base',
    series      text default '',            -- e.g. "Match Attax 2024/25"
    card_no     text default '',            -- number printed on the card
    rating      numeric,                    -- the rating printed on the card
    quantity    integer not null default 1,
    for_trade   boolean not null default false,
    note        text default '',
    created_at  timestamptz default now()
);

-- Added after the first cut of this migration; safe to re-run either way.
alter table card_packet add column if not exists subset   text not null default 'base';
alter table card_packet add column if not exists card_url text default '';
alter table card_packet add column if not exists card_no  text default '';

create index if not exists idx_card_packet_owner
    on card_packet (owner, created_at desc);
create index if not exists idx_card_packet_trade
    on card_packet (for_trade, created_at desc);


-- ------------------------------------------------------------
-- 2) WISHLIST — "I want THAT card out of YOUR packet".
--    Points at a specific card so the owner knows exactly what is wanted.
-- ------------------------------------------------------------
create table if not exists card_wishlist (
    id         bigint generated by default as identity primary key,
    username   text not null,               -- who wants it
    card_id    bigint not null,             -- -> card_packet.id
    owner      text not null,               -- packet owner at the time of wishing
    created_at timestamptz default now(),
    unique (username, card_id)
);

create index if not exists idx_card_wishlist_owner on card_wishlist (owner);
create index if not exists idx_card_wishlist_user  on card_wishlist (username);


-- ------------------------------------------------------------
-- 3) TRADES — an offer of cards from your packet for cards from theirs.
--    offer_ids / want_ids are comma-separated card_packet ids; the
--    swap is only applied when the receiver accepts.
-- ------------------------------------------------------------
create table if not exists card_trades (
    id          bigint generated by default as identity primary key,
    from_user   text not null,
    to_user     text not null,
    offer_ids   text not null default '',   -- cards the proposer gives
    want_ids    text not null default '',   -- cards the proposer wants
    -- Human-readable snapshot of each side, taken when the offer is made. Once
    -- a trade settles the card rows move (or merge), so the ids alone can no
    -- longer describe what was swapped — these keep the history readable.
    offer_label text default '',
    want_label  text default '',
    message     text default '',
    status      text not null default 'pending',  -- pending | accepted | declined | cancelled | stale
    created_at  timestamptz default now(),
    resolved_at timestamptz
);

alter table card_trades add column if not exists offer_label text default '';
alter table card_trades add column if not exists want_label  text default '';

create index if not exists idx_card_trades_to
    on card_trades (to_user, status, created_at desc);
create index if not exists idx_card_trades_from
    on card_trades (from_user, status, created_at desc);
