-- ============================================================
--  Cyvathon — Interests + Videos + Blogs migration
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

-- 1) Interests: a comma-separated list of interest keys on each citizen
alter table cybucks add column if not exists interests text default '';

-- 2) Videos platform
create table if not exists videos (
    id          bigint generated by default as identity primary key,
    username    text not null,
    title       text not null,
    url         text not null,          -- embed-ready URL (youtube/embed or direct file)
    kind        text default 'youtube', -- 'youtube' | 'file'
    description text default '',
    created_at  timestamptz default now()
);
create index if not exists idx_videos_created on videos (id desc);

create table if not exists video_comments (
    id         bigint generated by default as identity primary key,
    video_id   bigint not null,
    username   text not null,
    body       text not null,
    created_at timestamptz default now()
);
create index if not exists idx_video_comments on video_comments (video_id);

-- 3) Blogs platform
create table if not exists blogs (
    id         bigint generated by default as identity primary key,
    username   text not null,
    title      text not null,
    body       text not null,
    created_at timestamptz default now()
);
create index if not exists idx_blogs_created on blogs (id desc);

create table if not exists blog_comments (
    id         bigint generated by default as identity primary key,
    blog_id    bigint not null,
    username   text not null,
    body       text not null,
    created_at timestamptz default now()
);
create index if not exists idx_blog_comments on blog_comments (blog_id);

create table if not exists blog_likes (
    id         bigint generated by default as identity primary key,
    blog_id    bigint not null,
    username   text not null,
    created_at timestamptz default now(),
    unique (blog_id, username)
);
create index if not exists idx_blog_likes on blog_likes (blog_id);
