-- ============================================================
--  Cyvathon — Cyvaprint
--  Citizens upload a document; a Cyvazon courier prints it and delivers it.
--  Each page costs the Treasury's rate (black & white or colour), paid up
--  front. If it isn't delivered within one working day (weekends excluded),
--  the Treasury refunds it in full.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
--  Also create a PUBLIC Storage bucket named 'prints' (couriers open the file
--  to print it) — the app tries to create it, but make it public if uploads fail.
-- ============================================================

create table if not exists print_jobs (
    id           bigint generated by default as identity primary key,
    username     text not null,
    file_url     text not null,
    file_name    text default '',
    pages        int not null default 1,
    copies       int not null default 1,
    color        boolean not null default false,
    cost         numeric not null default 0,
    status       text not null default 'ordered',   -- ordered | delivered | refunded | cancelled
    delivery_id  bigint,                             -- the Cyvazon parcel carrying it
    refunded     boolean not null default false,
    note         text default '',
    created_at   timestamptz default now(),
    due_at       timestamptz,                        -- one working day after the order
    delivered_at timestamptz
);
create index if not exists idx_print_user on print_jobs (username, id desc);
create index if not exists idx_print_delivery on print_jobs (delivery_id);
create index if not exists idx_print_status on print_jobs (status, id desc);
