-- ============================================================
--  Cyvathon — Cyvapay migration
--  Payment links a citizen can put on any website, and the ledger
--  of what came in through them.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

-- ------------------------------------------------------------
-- 1) PAYMENT LINKS
--    `code` is the public handle that appears in the URL and in the
--    embed snippet. It is generated with secrets.token_urlsafe, so it
--    is unguessable — knowing one link tells you nothing about others.
--    The AMOUNT LIVES HERE, never in the request: a payer cannot talk
--    the gateway into charging a different figure.
-- ------------------------------------------------------------
create table if not exists cyvapay_links (
    id          bigint generated by default as identity primary key,
    code        text not null unique,
    owner       text not null,               -- the citizen who gets paid
    company_id  bigint,                      -- or their company, if set
    title       text not null,
    description text default '',
    currency    text not null default 'cybucks',
    amount      numeric not null default 0,  -- fixed price; 0 when flexible
    flexible    boolean not null default false,  -- payer names the amount
    min_amount  numeric not null default 1,
    max_amount  numeric not null default 100000,
    reusable    boolean not null default true,   -- false = one payment only
    redirect_url text default '',            -- where to send the payer afterwards
    active      boolean not null default true,
    uses        integer not null default 0,
    total_taken numeric not null default 0,
    created_at  timestamptz default now(),
    expires_at  timestamptz
);

create index if not exists idx_cyvapay_links_owner on cyvapay_links (owner, created_at desc);


-- ------------------------------------------------------------
-- 2) PAYMENTS — the receipt ledger. `ref` is the receipt number shown
--    to both sides so a merchant can match a payment to an order.
-- ------------------------------------------------------------
create table if not exists cyvapay_payments (
    id         bigint generated by default as identity primary key,
    ref        text not null unique,
    code       text not null,                -- the link it came through
    payee      text not null,                -- citizen credited
    company_id bigint,                       -- or the company credited
    payer      text not null,
    amount     numeric not null,
    currency   text not null default 'cybucks',
    title      text default '',
    note       text default '',              -- payer's own reference
    created_at timestamptz default now()
);

create index if not exists idx_cyvapay_pay_payee on cyvapay_payments (payee, created_at desc);
create index if not exists idx_cyvapay_pay_payer on cyvapay_payments (payer, created_at desc);
create index if not exists idx_cyvapay_pay_code  on cyvapay_payments (code);


-- ------------------------------------------------------------
-- 3) CONFIG — the President can close the gateway or take a fee.
--    The fee defaults to 0: Cyvapay is free to use.
-- ------------------------------------------------------------
alter table config add column if not exists cyvapay_open boolean default true;
alter table config add column if not exists cyvapay_fee  numeric default 0;

insert into config (id) values (1) on conflict (id) do nothing;
