-- ============================================================
--  Cyvathon — Justice & Cabinet migration
--  Jail, court sentencing, criminal records, ministry applications.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

-- ------------------------------------------------------------
-- 1) JAIL — a citizen serving time sees only the jail page
-- ------------------------------------------------------------
alter table cybucks add column if not exists jailed_until timestamptz;
alter table cybucks add column if not exists jail_reason  text;
alter table cybucks add column if not exists jailed_by    text;

create index if not exists idx_cybucks_jailed on cybucks (jailed_until);


-- ------------------------------------------------------------
-- 2) CRIMINAL RECORDS
--    Distinct from the free-text `records` table, which is a general
--    life-history feed. These are structured convictions: they carry a
--    fine and/or jail term, and they gate eligibility for office.
-- ------------------------------------------------------------
create table if not exists criminal_records (
    id         bigint generated by default as identity primary key,
    username   text not null,
    kind       text not null default 'fine',   -- 'fine' | 'jail' | 'both'
    fine       numeric default 0,              -- CB actually collected
    jail_days  numeric default 0,
    reason     text default '',
    case_id    bigint,                         -- set when it came from a court case
    issued_by  text not null,
    spent      boolean default false,          -- pardoned, or served and expunged
    created_at timestamptz default now()
);

create index if not exists idx_crimrec_user
    on criminal_records (username, spent, created_at desc);


-- ------------------------------------------------------------
-- 3) MINISTRY APPLICATIONS
--    A citizen applies for a vacant ministry. Once enough citizens have
--    applied, an election opens automatically.
-- ------------------------------------------------------------
create table if not exists ministry_applications (
    id          bigint generated by default as identity primary key,
    ministry_id bigint not null,
    username    text not null,
    statement   text default '',
    status      text default 'pending',   -- pending | elected | closed | withdrawn
    created_at  timestamptz default now(),
    unique (ministry_id, username)
);

create index if not exists idx_minapp
    on ministry_applications (ministry_id, status);


-- Link a poll back to the ministry it was opened for, so closing the
-- poll can install the winner as that minister.
alter table polls add column if not exists ministry_id bigint;


-- ------------------------------------------------------------
-- 4) CONFIG — President-tunable levers for the justice system
--    record_expiry_days = 0 means a conviction bars you from office
--    forever. Set it to e.g. 30 to let convictions become spent.
-- ------------------------------------------------------------
alter table config add column if not exists record_expiry_days      numeric default 0;
alter table config add column if not exists ministry_min_applicants numeric default 4;
alter table config add column if not exists fine_bars_office        boolean default true;

insert into config (id) values (1) on conflict (id) do nothing;


-- ------------------------------------------------------------
-- 5) COURT — a verdict can now carry a jail term as well as a fine
-- ------------------------------------------------------------
alter table court_cases add column if not exists jail_days numeric default 0;
