-- ============================================================
--  Cyvathon — Cyvalend (the lending library) migration
--  Borrow the calculator you forgot; give back what you borrowed.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

-- ------------------------------------------------------------
-- 1) THE SHELF — things citizens are willing to lend.
--    An item is either on the shelf, out on loan, or retired by
--    its owner. `deposit` is optional and refunded on return; it
--    exists so a lender can protect something they care about.
-- ------------------------------------------------------------
create table if not exists lend_items (
    id          bigint generated by default as identity primary key,
    owner       text not null,
    name        text not null,
    category    text not null default 'other',
    description text default '',
    image_url   text default '',
    condition   text default 'good',        -- new | good | worn
    deposit     numeric not null default 0, -- CB held from the borrower
    max_days    numeric not null default 1, -- longest loan the owner allows
    status      text not null default 'available',  -- available | out | retired
    times_lent  integer not null default 0,
    created_at  timestamptz default now()
);

create index if not exists idx_lend_items_shelf on lend_items (status, created_at desc);
create index if not exists idx_lend_items_owner on lend_items (owner);


-- ------------------------------------------------------------
-- 2) LOANS — one row per borrow, from the ask to the return.
--    The OWNER confirms the return, the same way the recipient
--    confirms a Cyvazon parcel: the person who is owed something
--    is the one who says it arrived.
-- ------------------------------------------------------------
create table if not exists lend_loans (
    id           bigint generated by default as identity primary key,
    item_id      bigint not null,
    owner        text not null,
    borrower     text not null,
    days         numeric not null default 1,
    reason       text default '',
    status       text not null default 'requested',
    -- requested | declined | cancelled | out | returned
    deposit_held numeric not null default 0,
    delivery_id  bigint,                    -- Cyvazon parcel, when delivered
    requested_at timestamptz default now(),
    decided_at   timestamptz,
    due_at       timestamptz,
    returned_at  timestamptz,
    late         boolean not null default false,
    note         text default ''
);

create index if not exists idx_lend_loans_item     on lend_loans (item_id, status);
create index if not exists idx_lend_loans_borrower on lend_loans (borrower, status);
create index if not exists idx_lend_loans_owner    on lend_loans (owner, status);


-- ------------------------------------------------------------
-- 3) CONFIG — the President can close the library or cap deposits.
-- ------------------------------------------------------------
alter table config add column if not exists lend_open        boolean default true;
alter table config add column if not exists lend_max_deposit numeric default 200;

insert into config (id) values (1) on conflict (id) do nothing;
