-- ============================================================
--  Cyvathon — National Delivery Service migration
--  Couriers, parcels, and the levy that pays for free delivery.
--  Safe & idempotent. Paste into the Supabase SQL editor and run.
-- ============================================================

-- ------------------------------------------------------------
-- 1) COURIERS — citizens signed up to run parcels around school.
--    Paid a weekly wage from the Treasury, which is why the wage
--    lives in `config` and not in a hard-coded table.
-- ------------------------------------------------------------
create table if not exists couriers (
    id          bigint generated by default as identity primary key,
    username    text not null unique,
    -- Signing up is an APPLICATION. The President vets couriers from the
    -- delivery admin panel before anyone can pick up other people's things.
    status      text not null default 'pending',   -- pending | approved | rejected
    decided_by  text,
    decided_at  timestamptz,
    active      boolean not null default true,
    covers      text default '',        -- classes/areas this courier can reach
    note        text default '',
    deliveries  integer not null default 0,   -- completed runs, for the leaderboard
    hired_at    timestamptz default now(),
    left_at     timestamptz
);

alter table couriers add column if not exists status     text not null default 'pending';
alter table couriers add column if not exists decided_by text;
alter table couriers add column if not exists decided_at timestamptz;

create index if not exists idx_couriers_active on couriers (active, status);


-- ------------------------------------------------------------
-- 2) DELIVERIES — one parcel each.
--    `kind` records what created it, so a marketplace sale or a card
--    trade can't be quietly settled without the goods actually moving:
--      market  -> ref_id is market_items.id
--      card    -> ref_id is card_trades.id
--      custom  -> a citizen sending anything to anyone
-- ------------------------------------------------------------
create table if not exists deliveries (
    id            bigint generated by default as identity primary key,
    kind          text not null default 'custom',
    ref_id        bigint,
    item_label    text not null default '',
    sender        text not null,          -- hands the item over
    recipient     text not null,          -- receives it
    requested_by  text not null,
    pickup_class  text default '',
    pickup_area   text default '',
    dropoff_class text default '',
    dropoff_area  text default '',
    notes         text default '',
    status        text not null default 'open',  -- open | claimed | picked_up | delivered | cancelled
    courier       text,
    created_at    timestamptz default now(),
    claimed_at    timestamptz,
    delivered_at  timestamptz
);

create index if not exists idx_deliveries_status  on deliveries (status, created_at desc);
create index if not exists idx_deliveries_courier on deliveries (courier, status);
create index if not exists idx_deliveries_people  on deliveries (sender, recipient);


-- ------------------------------------------------------------
-- 3) The classroom a citizen is normally found in, so delivery
--    forms can pre-fill instead of asking every single time.
-- ------------------------------------------------------------
alter table cybucks add column if not exists home_class      text default '';
alter table cybucks add column if not exists home_area       text default '';
-- Courier wages are paid on their own clock, separate from the salary
-- a citizen already draws for their designation.
alter table cybucks add column if not exists last_courier_pay timestamptz;


-- ------------------------------------------------------------
-- 4) CONFIG — the President tunes the service from the admin panel.
--    Delivery is free to use, so the nation pays for it collectively:
--    `delivery_levy` is charged on top of VAT while the service runs.
--    Set it to 0 to fund couriers out of general revenue instead.
-- ------------------------------------------------------------
alter table config add column if not exists courier_wage    numeric default 500;
alter table config add column if not exists delivery_levy   numeric default 0.05;
alter table config add column if not exists delivery_open    boolean default true;

insert into config (id) values (1) on conflict (id) do nothing;
